[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "always"

# Service configuration for Mars Bridge Relayer
[[services]]
name = "mars-bridge-relayer"
source = "."
start_command = "npm run bridge:start:production"

[services.variables]
NODE_ENV = "production"
PORT = "3000"
HEALTH_CHECK_PORT = "8080"
# Bridge configuration will be set via Railway environment variables
BRIDGE_CONTRACT_ADDRESS = "0xe0b596B25c67B8d4c37646C19dbBFfc2bE38A7Ba"
MARS_MINT_ADDRESS = "uNcM3H28XL12sZL2LXnrUG5EnfTRQx9wb2ULh5hUF4b"
MARS_TOKEN_ACCOUNT = "29zqmJEVmhXrqbDSW5TJYdGzPLvJQKLXzLwTWjqLf3J4"
L1_RPC_URL = "https://rpc.marscredit.xyz:443"
SOLANA_RPC_URL = "https://api.mainnet-beta.solana.com"

# Frontend service (optional)
[[services]]
name = "mars-bridge-frontend"
source = "."
start_command = "npm run build && npm start"

[services.variables]
NODE_ENV = "production"
PORT = "3000"
# Frontend environment variables
NEXT_PUBLIC_BRIDGE_CONTRACT_ADDRESS = "0xe0b596B25c67B8d4c37646C19dbBFfc2bE38A7Ba"
NEXT_PUBLIC_MARS_MINT_ADDRESS = "uNcM3H28XL12sZL2LXnrUG5EnfTRQx9wb2ULh5hUF4b"
NEXT_PUBLIC_SOLANA_RPC_URL = "https://api.mainnet-beta.solana.com"
NEXT_PUBLIC_L1_RPC_URL = "https://rpc.marscredit.xyz:443" 